### PR TITLE
Fix/remove warnings

### PR DESCRIPTION
**Pull request by ThoSe1990**

### CODE REVIEW

**Comment by kreuzberger** [comment]
I just tested the compilation cause i am wondering why it does not work for me.
When i compile the current version of the branch on ubuntu24 i get
```
FAILED: examples/CMakeFiles/example.dir/step_definition.cpp.o 
/usr/bin/c++ -DJSON_DIAGNOSTICS=0 -DJSON_USE_IMPLICIT_CONVERSIONS=1 -I/tmp/cwt-cucumber/src -I/tmp/cwt-cucumber/build/src -isystem   ~/.conan/data/nlohmann_json/3.10.5+2/sx/testing/package/1858ea7ebb93cd35bb7c35926cb09d1f090ea1f6/include -O3 -DNDEBUG -std=gnu++20 -MD -MT examples/CMakeFiles/example.dir/step_definition.cpp.o -MF examples/CMakeFiles/example.dir/step_definition.cpp.o.d -o examples/CMakeFiles/example.dir/step_definition.cpp.o -c /tmp/cwt-cucumber/examples/step_definition.cpp
/tmp/cwt-cucumber/examples/step_definition.cpp: In function ‘cuke::internal::any custom_date(std::vector<cuke::value>::const_iterator, std::size_t)’:
/tmp/cwt-cucumber/examples/step_definition.cpp:27:46: error: call of overloaded ‘basic_string(const cuke::value&)’ is ambiguous
   27 |   begin.month = std::string(CUKE_PARAM_ARG(1));
```

If i look in the build-gcc build (which is successfull) i see that the lines of the cmake configure of the project are different:
```
-- The C compiler identification is GNU 13.2.0
-- The CXX compiler identification is GNU 13.2.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
```
And your build seems to use CLANG for the build of the library? Or do i understand something wrong?
From the log
```
Install finished successfully
-- Using Conan toolchain: /__w/cwt-cucumber/cwt-cucumber/build_gcc/conan_toolchain.cmake
-- Conan toolchain: C++ Standard 20 with extensions ON
-- The C compiler identification is Clang 17.0.6
-- The CXX compiler identification is Clang 17.0.6
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
```

**Comment by ThoSe1990** [comment]
right, I'll refactor the pipelines in this PR. it was about time to do.

**Comment by ThoSe1990** [comment]
ok so the gcc build now uses gcc and i moved the windows build to github actions. but i think i do something wrong with dynamic/static linking there. unfortunately i don't have access to a windows computer at the moment. 

And: I updated the `README` and added a section for using strings in a custom type parameter. Its a bit limited, but still fine.

**Comment by ThoSe1990** [comment]
All good now, I found it. MSVC does different static initialization and threw an exception which caused all the problems. Still, it was worth it, because I finally cleaned up the pipelines, and I didn't even know that gcc actually builds with clang. So thats a good end for today, and thanks for the thorough look :)

**Comment by kreuzberger** [comment]
I run the latest commits now on my windows machine.
Setting the policy has no serious effect, the MTd MDd flags are set correctly even if the policy is omitted

Executing the bin/example.exe with path to the feature files will NOT run the examples, it gets stucked (seems like infinite loop).

**Comment by kreuzberger** [comment]
from 1_first_scenario.feature i seems the error comes from step "WHEN" "I place {int} x {string}..."
if size_t is used for count on windows a very large (invalid, uninitialized, whatever) value (14829735428352901121) for count is returned.
if "int" is used, everything works as expected

**Comment by ThoSe1990** [comment]
I just noticed this too, i fixed it in https://github.com/ThoSe1990/cwt-cucumber/pull/58/commits/4ab219727462e69c6ccf6ea208067443e9d4a2ab. In earlier versions i had a specialization for std::size_t which was removed recently but there we are again

**Comment by ThoSe1990** [comment]
So to summarize: 
- I added a MSVC_STATIC option for a msvc static linking build 
- MSVC threw an exception caused by wrong static initialization -> fixed in https://github.com/ThoSe1990/cwt-cucumber/commit/8b133f565bbd45d8870d6654e6472ba8f7986309
- MSVC treats `std::size_t` differntly. The `std::size_t` version was  removed with custom parameter types and I didn't notice because the pipeline did not cover the examples. Re-implemented in https://github.com/ThoSe1990/cwt-cucumber/commit/4ab219727462e69c6ccf6ea208067443e9d4a2ab
- Windows pipeline moved from azure to github actions -> runs examples and unittests 
- GCC pipeline took by mistake clang which is fixed now.

**Pull request merged**
